const words = [
   
    "apple", "ball", "cat", "dog", "egg", "fish", "game", "home", "ice", "jump",
    "kite", "lamp", "milk", "nest", "open", "park", "quit", "rain", "star", "tree",
    "ugly", "vase", "wind", "yarn", "zero", "bold", "calm", "dark", "easy", "fast",
    "glad", "hard", "idle", "just", "keen", "lazy", "mild", "nice", "odd", "pure",
    "rich", "safe", "tall", "used", "vast", "warm", "young", "blue", "pink", "gold",
    "fire", "lake", "moon", "sand", "wave", "bird", "clay", "drum", "edge", "flip",
    "glow", "haze", "iron", "jade", "knot", "leaf", "mist", "noon", "oval", "plum",
    "quiz", "rose", "silk", "twig", "urge", "vine", "wolf", "exit", "yawn", "zinc",
    "acid", "beam", "cord", "dusk", "echo", "foam", "gust", "hive", "iris", "jolt",
    "kelp", "lava", "myth", "node", "opal", "pine", "reef", "smog", "tide", "unit",

   
    "computer", "javascript", "library", "function", "object", "variable",
    "internet", "keyboard", "monitor", "program", "network", "browser", "desktop",
    "cartoon", "captain", "diamond", "eastern", "factory", "garlic", "harvest",
    "insects", "journey", "kitchen", "lantern", "machine", "natural", "organic",
    "pacific", "quarter", "reality", "science", "teacher", "uniform", "village",
    "weather", "express", "balance", "cabinet", "dolphin", "element", "freedom",
    "gravity", "history", "imagine", "justice", "kingdom", "leather", "morning",
    "nothing", "opinion", "passion", "quality", "respect", "silence", "thunder",
    "unusual", "victory", "warrior", "finance", "gesture", "hundred", "blanket",
    "channel", "defense", "episode", "failure", "genuine", "habitat", "illegal",
    "journal", "ketchup", "license", "maximum", "nuclear", "outside", "perfect",
    "quantum", "reflect", "snippet", "texture", "upgrade", "venture", "whisper",
    "ancient", "breadth", "content", "density", "ecology", "essence", "fission",
    "glitter", "horizon", "integer", "javelin", "kinetic", "lattice", "mindset",
    "nostalgia", "obvious", "phantom", "radiant", "savanna", "tangent", "umbral",
    "velvet", "warden", "eclipse", "feather", "glacier", "harvest", "impulse",
    "lantern", "meadow", "nectar", "oracle", "pebble", "quartz", "ribbon", "spiral",
    "temple", "unfold", "vortex", "willow", "zenith", "abyss", "bridge", "canopy",
    "dagger", "embark", "frenzy", "gravel", "herald", "ignite", "jungle", "kindle",

    "synchronization", "implementation", "asynchronous", "authentication",
    "configuration", "optimization", "architecture", "multithreading",
    "accomplishment", "breakthrough", "circumstances", "collaboration",
    "demonstration", "encyclopedia", "functionality", "globalization",
    "hallucination", "independence", "jurisdiction", "knowledgeable",
    "manufacturing", "notifications", "orchestration", "parallelization",
    "qualification", "reconnaissance", "sophisticated", "transformation",
    "understanding", "visualization", "vulnerability", "approximation",
    "biodiversity", "civilization", "decomposition", "electromagnetic",
    "fragmentation", "generalization", "hypothetical", "initialization",
    "justification", "modernization", "normalization", "opportunities",
    "prioritization", "quantification", "rationalization", "serialization",
    "tokenization", "unprecedented", "abstraction", "benchmarking",
    "cryptocurrency", "decentralized", "encapsulation", "fingerprinting",
    "infrastructure", "interpolation", "microservices", "middleware",
    "obfuscation", "polymorphism", "refactoring", "scalability",
    "specification", "cryptography", "compression", "concurrency",
    "deprecation", "distributed", "enumeration", "inheritance",
    "integration", "propagation", "recursion", "regression",
    "replication", "simulation", "validation", "abstraction",

    "acknowledgement", "classifications", "compartmentalize", "congratulations",
    "counterproductive", "decentralization", "electromagnetic", "enlightenment",
    "entrepreneurship", "environmentalism", "experimentation", "extraterrestrial",
    "fundamental", "internationally", "investigations", "liberalization",
    "misunderstanding", "multidimensional", "nondeterministic", "overcomplication",
    "personalization", "photosynthesis", "postmodernism", "probabilistic",
    "procrastination", "professionalism", "proportionality", "psychologically",
    "recommendation", "representatives", "responsibilities", "revolutionary",
    "simultaneously", "specifications", "standardization", "straightforward",
    "subconsciously", "sustainability", "systematically", "telecommunication",
    "thermodynamics", "underestimating", "unintelligible", "unsubstantiated",
    "weatherproofing", "worcestershire", "xenotransplant", "zealousness",
    "bioinformatics", "circumnavigation", "conscientiousness", "counterintuitive",
    "crystallization", "deoxyribonucleic", "disproportionate", "dysfunctionality",
    "electrochemical", "excommunication", "experimentation", "extrapolation",
    "geopolitical", "heterogeneous", "interconnected", "interdisciplinary",
    "malfunctioning", "metamorphosis", "miscommunication", "multifaceted",
    "nanotechnology", "neuroplasticity", "noncompliance", "overengineering",
    "paleontological", "parliamentarian", "photojournalism", "poststructuralism",
    "predetermination", "presuppositions", "problematically", "programmatically",
];

export default words;